# Generated by Django 3.1.2 on 2020-12-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNow', '0002_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='product',
        ),
        migrations.AddField(
            model_name='myorder',
            name='product',
            field=models.ManyToManyField(related_name='myorder', to='ShopNow.Product'),
        ),
    ]
