# Generated by Django 3.1.2 on 2020-12-08 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopNow', '0004_auto_20201208_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='product',
        ),
        migrations.AddField(
            model_name='myorder',
            name='productName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShopNow.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
