# Generated by Django 3.1.2 on 2020-12-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopNow', '0005_auto_20201208_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ShopNow.product'),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username1', to=settings.AUTH_USER_MODEL),
        ),
    ]
