# Generated by Django 3.1.2 on 2020-12-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNow', '0012_myorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorder',
            old_name='productName',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='user',
            new_name='orderBy',
        ),
    ]
