# Generated by Django 3.1.2 on 2020-12-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNow', '0014_auto_20201209_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder2',
            name='orderBy',
        ),
    ]
