# Generated by Django 3.1.2 on 2020-12-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopNow', '0016_delete_myorder2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrdersNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDateAndTime', models.DateTimeField(null=True)),
                ('orderByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productOrder', models.ManyToManyField(related_name='orderByUser', to='ShopNow.Product')),
            ],
        ),
    ]
