# Generated by Django 3.1.2 on 2020-12-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNow', '0017_myordersnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myordersnew',
            name='orderDateAndTime',
        ),
        migrations.AlterField(
            model_name='mycart',
            name='productName',
            field=models.ManyToManyField(related_name='productnames', to='ShopNow.Product'),
        ),
        migrations.RemoveField(
            model_name='myordersnew',
            name='productOrder',
        ),
        migrations.AddField(
            model_name='myordersnew',
            name='productOrder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ShopNow.product'),
            preserve_default=False,
        ),
    ]
