# Generated by Django 3.1.2 on 2020-12-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopNow', '0019_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsRelatedName', to='ShopNow.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewerrelatedName', to=settings.AUTH_USER_MODEL),
        ),
    ]
