# Generated by Django 3.1.2 on 2020-12-12 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShopNow', '0020_auto_20201212_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingRalatedName', to='ShopNow.product')),
            ],
        ),
    ]
